[tool.towncrier]

directory = "changelog.d"
filename = "CHANGELOG.md"
title_format = "## [v{version}](https://github.com/makukha/multipython/releases/tag/v{version})"
issue_format = "[#{issue}](https://github.com/makukha/multipython/issues/{issue})"

type = [
  {name = "Security ‚ö†Ô∏è", directory = "security", showcontent = true},
  {name = "Breaking üî•", directory = "breaking", showcontent = true},
  {name = "Removed üí•", directory = "removed", showcontent = true},
  {name = "Deprecated ‚ùÑÔ∏è", directory = "deprecated", showcontent = true},
  {name = "Added üåø", directory = "added", showcontent = true},
  {name = "Changed", directory = "changed", showcontent = true},
  {name = "Fixed", directory = "fixed", showcontent = true},
  {name = "Docs", directory = "docs", showcontent = true},
  {name = "Misc", directory = "misc", showcontent = true},
]
